- name: Check PostgreSQL service status
  ansible.builtin.command: "pg_ctl -D {{ postgresql_user_data_dir }} status"
  environment:
    PATH: "{{ user_bin_dir }}:{{ ansible_env.PATH }}"
  register: postgresql_status
  changed_when: false
  # rc 0 => postgres is installed
  # rc 2 => postgres is not installed or not symlinked
  # rc 3 => DBMS folder is correct but the server is not running
  # rc 4 => database data does not exist at `postgresql_user_data_dir` or is corrupted
  failed_when: postgresql_status.rc not in postgresql_success_rc
