# Responsible for installing postgres and symlinking executables

- name: Ensure PostgreSQL is installed
  community.general.homebrew:
    name: "postgresql@{{ postgresql_version }}"
    state: present

- name: Ensure brew PostgreSQL service is stopped
  ansible.builtin.command: brew services stop postgresql@{{ postgresql_version }}
  changed_when: true

- name: Get list of PostgreSQL executables
  ansible.builtin.find:
    paths: "{{ postgresql_brew_bin_dir }}"
    file_type: file
    recurse: false
  register: list_postgres_executables

- name: Ensure user bin directory exists
  ansible.builtin.file:
    path: "{{ user_bin_dir }}"
    state: directory
    mode: "0755"

- name: Create symlinks for all PostgreSQL executables in ~/bin
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ user_bin_dir }}/{{ item.path | basename }}"
    state: link
  loop: "{{ list_postgres_executables.files }}"
