---
# PostgreSQL Management Tasks
# This playbook ensures PostgreSQL is installed, initialized, and running.

- name: Check PostgreSQL service status
  ansible.builtin.include_tasks: check_status.yaml
  vars:
    postgresql_success_rc: [0, 2, 3, 4]

- name: Start PostgreSQL service, install and initdb if required
  ansible.builtin.include_tasks: start.yaml
  when: postgresql_status.rc != 0
