- name: Check if Grafana binary symlink exists
  ansible.builtin.stat:
    path: "{{ user_bin_dir }}/grafana"
  register: grafana_symlink

- name: Install Grafana
  ansible.builtin.include_role:
    name: prom
    tasks_from: installation.yaml
  vars:
    prom_service_name: grafana
    prom_download_url: >
      https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.darwin-arm64.tar.gz
    prom_archive_name: grafana-v{{ grafana_version }}/bin
    prom_executables: [grafana, grafana-cli, grafana-server]
  when:
    - not grafana_symlink.stat.exists

- name: Copy Grafana config
  ansible.builtin.include_tasks: copy_config.yaml

# /Users/akash/bin/grafana server --config ./roles/grafana/files/defaults.ini --homepath /Users/akash/grafana/grafana-v{{ grafana_version }}.0
- name: Ensure Grafana logs directory exists
  ansible.builtin.file:
    path: "{{ grafana_logs_dir }}"
    state: directory
    mode: "0755"

- name: Start Grafana service
  ansible.builtin.include_role:
    name: prom
    tasks_from: start.yaml
  vars:
    prom_service_name: grafana
    prom_service_port: "{{ grafana_port }}"
    prom_start_cmd: >-
      {{ user_bin_dir }}/grafana server
      --config {{ grafana_cfg_file }}
      --homepath {{ grafana_home_dir }}
    prom_logs_dir: "{{ grafana_logs_dir }}"
