# Vars:
#   service_name, service_port

- name: Check grafana service status
  ansible.builtin.uri:
    url: "http://localhost:{{ grafana_service_port }}"
    return_content: false
  register: grafana_service
  changed_when: false
  failed_when: false
