bin_path: ${USER_BIN_PATH}
cfg_path: ${USER_CFG_PATH}
groups:
services:
  - name: "jellyfin"
    version: "10.9.11"
    ports: 
      - 8096
    logs_dir: ${JELLYFIN_LOGS_PATH}
    installer:
      type: binary
      download_url: "https://blr1.mirror.jellyfin.org/files/server/macos/stable/v${version}/arm64/jellyfin_${version}-arm64.dmg"
      is_archive: true
      install_path: ${JELLYFIN_INSTALL_PATH}
      executables:
        jellyfin: Jellyfin.app/Contents/MacOS/jellyfin
