- name: Install and configure services on macOS M1
  hosts: localhost
  connection: local
  become: false
  vars:
    user_bin_dir: "{{ ansible_env.HOME }}/bin"
    user_cfg_dir: "{{ ansible_env.HOME }}/cfg"
  tasks:
    - name: Stop PostgreSQL
      ansible.builtin.include_role:
        name: postgresql
        tasks_from: stop.yaml

    - name: Stop prometheus
      ansible.builtin.include_role:
        name: prometheus
        tasks_from: stop.yaml
