# Vars:
#   prom_service_name, prom_service_port, prom_start_cmd, prom_logs_dir

- name: Start {{ prom_service_name }} service
  ansible.builtin.shell: >
    {{ prom_start_cmd }}
    > {{ prom_logs_dir }}/{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.log 2>&1 &
  changed_when: true

- name: Wait for Prometheus to be up
  ansible.builtin.uri:
    url: "http://localhost:{{ prom_service_port }}"
    return_content: false
  register: wait_for_prometheus
  retries: 5
  delay: 10
  until: wait_for_prometheus.status == 200
