# Vars:
#   service_name, service_port

- name: Check {{ prom_service_name }} service status
  ansible.builtin.uri:
    url: "http://localhost:{{ prom_service_port }}"
    return_content: false
  register: prom_service
  changed_when: false
  failed_when: false
