- name: Check node_exporter service is running
  ansible.builtin.uri:
    url: "http://localhost:{{ node_exporter_port }}"
    return_content: false
  register: node_exporter_status
  changed_when: false
  failed_when: false

- name: Start node_exporter service, install if required
  ansible.builtin.include_tasks: start.yaml
  when: node_exporter_status.status == -1 and 'Connection refused' in node_exporter_status.msg
