- name: Check node_exporter service status
  ansible.builtin.include_role:
    name: prom
    tasks_from: status.yaml
  vars:
    prom_service_name: node_exporter
    prom_service_port: "{{ node_exporter_port }}"

- name: Start node_exporter service, install and initdb if required
  ansible.builtin.include_tasks: start.yaml
  when: prom_service.status == -1 and 'Connection refused' in prom_service.msg
