- name: Check if node_exporter binary symlink exists
  ansible.builtin.stat:
    path: "{{ user_bin_dir }}/node_exporter"
  register: node_exporter_symlink

- name: Install node_exporter
  ansible.builtin.include_role:
    name: prom
    tasks_from: installation.yaml
  vars:
    prom_service_name: node_exporter
    prom_download_url: "https://github.com/prometheus/node_exporter/releases/\
      download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.darwin-arm64.tar.gz"
    prom_archive_name: node_exporter-{{ node_exporter_version }}.darwin-arm64
    prom_executables: [node_exporter]
  when:
    - not node_exporter_symlink.stat.exists

- name: Start node_exporter service
  ansible.builtin.include_role:
    name: prom
    tasks_from: start.yaml
  vars:
    prom_service_name: node_exporter
    prom_service_port: "{{ node_exporter_port }}"
    prom_start_cmd: "{{ user_bin_dir }}/node_exporter"
    prom_logs_dir: "{{ node_exporter_logs_dir }}"
