- name: Check Prometheus service status
  ansible.builtin.include_role:
    name: prom
    tasks_from: status.yaml
  vars:
    prom_service_name: prometheus
    prom_service_port: "{{ prometheus_port }}"

- name: Start Prometheus service, install and initdb if required
  ansible.builtin.include_tasks: start.yaml
  when: prom_service.status == -1 and 'Connection refused' in prom_service.msg
