- name: Check Prometheus service is running
  ansible.builtin.uri:
    url: "http://localhost:{{ prometheus_port }}"
    return_content: false
  register: prometheus_status
  changed_when: false
  failed_when: false

- name: Start Prometheus service, install and initdb if required
  ansible.builtin.include_tasks: start.yaml
  when: prometheus_status.status == -1 and 'Connection refused' in prometheus_status.msg
