- name: Check if Prometheus binary symlink exists
  ansible.builtin.stat:
    path: "{{ user_bin_dir }}/prometheus"
  register: prometheus_symlink

- name: Install Prometheus
  ansible.builtin.include_role:
    name: prom
    tasks_from: installation.yaml
  vars:
    prom_service_name: prometheus
    prom_download_url: >
      https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.darwin-arm64.tar.gz
    prom_archive_name: prometheus-{{ prometheus_version }}.darwin-arm64
    prom_executables: [prometheus, promtool]
  when:
    - not prometheus_symlink.stat.exists

- name: Copy Prometheus config
  ansible.builtin.include_tasks: copy_config.yaml

- name: Ensure Prometheus logs directory exists
  ansible.builtin.file:
    path: "{{ prometheus_logs_dir }}"
    state: directory
    mode: "0755"

- name: Start Prometheus service
  ansible.builtin.include_role:
    name: prom
    tasks_from: start.yaml
  vars:
    prom_service_name: prometheus
    prom_service_port: "{{ prometheus_port }}"
    prom_start_cmd: >-
      {{ user_bin_dir }}/prometheus
      --config.file={{ prometheus_cfg_file }}
      --storage.tsdb.path={{ prometheus_data_dir }}
      --log.level=info
      --log.format=logfmt
    prom_logs_dir: "{{ prometheus_logs_dir }}"
