# Add encryption to the DB.
# This is currently not used and DB is encrypted while creating itself using initdb.

- name: Create new pg_hba.conf with SCRAM authentication
  community.postgresql.postgresql_pg_hba:
    dest: "{{ postgresql_brew_data_dir }}/pg_hba.conf"
    overwrite: true
    contype: host
    users: all
    source: all
    databases: all
    method: scram-sha-256

- name: Update PostgreSQL configuration to use password encryption
  community.builtin.lineinfile:
    path: "{{ postgresql_brew_data_dir }}/postgresql.conf"
    regexp: "^#?password_encryption ="
    line: "password_encryption = 'scram-sha-256'"
    state: present
