# Responsible for installing postgres and symlinking executables

- name: Ensure PostgreSQL is installed
  community.general.homebrew:
    name: "postgresql@{{ postgresql_version }}"
    state: present

- name: Stop PostgreSQL
  ansible.builtin.include_tasks: tasks/stop.yaml

- name: Get list of PostgreSQL executables
  ansible.builtin.find:
    paths: "{{ postgresql_brew_bin_dir }}"
    file_type: file
    recurse: false
  register: postgres_executables

- name: Ensure user bin directory exists
  ansible.builtin.file:
    path: "{{ user_bin_dir }}"
    state: directory
    mode: "0755"

- name: Create symlinks for all PostgreSQL executables in ~/bin
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ user_bin_dir }}/{{ item.path | basename }}"
    state: link
  loop: "{{ postgres_executables.files }}"
